{{- if .Values.services.api.ingress.enabled -}}
{{- $fullName := include "honeydipper.fullname" . -}}
{{- $ingressPath := .Values.services.api.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  {{- with .Values.daemon.namespace.name }}
  {{- if ne . "default" }}
  namespace: {{ . }}
  {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "honeydipper.name" . }}
    helm.sh/chart: {{ include "honeydipper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.services.api.ingress.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.services.api.ingress.tls }}
  tls:
  {{- range .Values.services.api.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  backend:
    serviceName: {{ $fullName }}-api
    servicePort: {{ $.Values.services.api.service.port }}
{{- end }}
