{{- with .Values.daemon.namespace }}
{{- if and (ne .name "default") (empty .use_existing) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
{{- end }}
